%YAML:1.0
---
model_type: PINHOLE
camera_name: p4
image_width: 1926
image_height: 1080
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 1166
   fy: 1166
   cx: 963
   cy: 540
